name: throwtrash
description: 今日のゴミ出し

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <=3.5.3"
  flutter: "^3.24.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  json_annotation: ^4.0.0
  meta: ^1.7.0
  shared_preferences: ^2.0.5
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_analytics: ^11.3.3
  uuid: ^4.2.1
  http: ^1.1.2
  json_serializable: ^6.3.1
  logger: ^2.0.2+1
  url_launcher: ^6.1.5
  uni_links: ^0.5.1
  fluttertoast: ^8.0.9
  firebase_crashlytics: ^4.1.3
  webview_flutter: ^4.0.6
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.2.19
  package_info_plus: ^8.1.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^19.1.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  mockito: ^5.2.0
  test: ^1.19.5
  analyzer: ^6.2.0
  code_builder: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - json/development/config.json
    - json/production/config.json

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  background_color: "#ffffff"
