name: throwtrash
description: 今日のゴミ出し

version: 1.0.0+1
environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: "^3.38.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  json_annotation: ^4.9.0
  meta: ^1.17.0
  shared_preferences: ^2.5.4
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_analytics: ^12.1.0
  uuid: ^4.2.1
  http: ^1.1.2
  json_serializable: ^6.11.2
  logger: ^2.0.2+1
  url_launcher: ^6.1.5
  uni_links: ^0.5.1
  fluttertoast: ^9.0.0
  firebase_crashlytics: ^5.0.6
  webview_flutter: ^4.13.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.7
  package_info_plus: ^9.0.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.10.4
  mockito: ^5.6.3
  test: ^1.26.3
  code_builder: ^4.11.1
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - json/development/config.json
    - json/production/config.json

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  background_color: "#ffffff"
